// Consent purpose/scope canonicalization and versioned consent hashes
// (Issue #1337).
//
// The hash vectors below were generated by the independent reference
// implementation in scripts/gen_consent_hash_vectors.py and are published:
// they must not change unless the canonical format changes.

use crate::*;
use soroban_sdk::testutils::{Address as _, Ledger as _};
use soroban_sdk::{BytesN, Env};

const SUBJECT_1: &str = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC6PV";
const SUBJECT_2: &str = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEGWF";
const RESEARCH_READ_MEDICAL_LAB_V1: &str =
    "395d259a443267342e008400d4767b40b64509c2f34c9edd055635e00fe59058";
const RESEARCH_READ_MEDICAL_LAB_V2: &str =
    "45e622197e67177600153a52acfa0d21fd2bd89257f085324ec0e49bc3004012";
const INSURANCE_ALL_SCOPES_V1: &str =
    "ab65cd37d69e6fec2dcafc4b1e0a1a1cd302b04f19f708727fdc7538520ab3f7";

// After the fixture pet's 2020 birthday, which must not be in the future.
const T0: u64 = 1_800_000_000;

const ALL_SCOPES: [ConsentScope; 4] = [
    ConsentScope::ReadMedical,
    ConsentScope::WriteMedical,
    ConsentScope::ReadLab,
    ConsentScope::EmergencyOnly,
];

fn hex_to_array(hex: &str) -> [u8; 32] {
    let mut out = [0u8; 32];
    let bytes = hex.as_bytes();
    for i in 0..32 {
        let hi = (bytes[2 * i] as char).to_digit(16).unwrap() as u8;
        let lo = (bytes[2 * i + 1] as char).to_digit(16).unwrap() as u8;
        out[i] = (hi << 4) | lo;
    }
    out
}

fn setup() -> (Env, PetChainContractClient<'static>, u64) {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().with_mut(|l| l.timestamp = T0);
    let contract_id = env.register_contract(None, PetChainContract);
    let client = PetChainContractClient::new(&env, &contract_id);
    let pet_id = register_pet(&env, &client);
    (env, client, pet_id)
}

fn register_pet(env: &Env, client: &PetChainContractClient) -> u64 {
    client.register_pet(
        &Address::generate(env),
        &String::from_str(env, "Buddy"),
        &String::from_str(env, "2020-01-01"),
        &Gender::Male,
        &Species::Dog,
        &String::from_str(env, "Golden Retriever"),
        &String::from_str(env, "Golden"),
        &25u32,
        &None,
        &PrivacyLevel::Public,
    )
}

fn scopes(env: &Env, list: &[ConsentScope]) -> Vec<ConsentScope> {
    let mut v = Vec::new(env);
    for s in list {
        v.push_back(s.clone());
    }
    v
}

fn subject(env: &Env, strkey: &str) -> Address {
    Address::from_string(&String::from_str(env, strkey))
}

// --- normalization ---

#[test]
fn purpose_codes_and_scope_bits_are_pinned() {
    assert_eq!(purpose_code(&ConsentType::Insurance), 1);
    assert_eq!(purpose_code(&ConsentType::Research), 2);
    assert_eq!(purpose_code(&ConsentType::PublicHealth), 3);
    assert_eq!(purpose_code(&ConsentType::Other), 4);

    assert_eq!(scope_bit(&ConsentScope::ReadMedical), 1);
    assert_eq!(scope_bit(&ConsentScope::WriteMedical), 2);
    assert_eq!(scope_bit(&ConsentScope::ReadLab), 4);
    assert_eq!(scope_bit(&ConsentScope::EmergencyOnly), 8);
}

#[test]
fn order_and_duplicates_do_not_change_the_canonical_mask() {
    let env = Env::default();
    let a = scopes(&env, &[ConsentScope::ReadLab, ConsentScope::ReadMedical]);
    let b = scopes(
        &env,
        &[
            ConsentScope::ReadMedical,
            ConsentScope::ReadLab,
            ConsentScope::ReadLab,
        ],
    );
    assert_eq!(canonical_scope_mask(&a), Some(0b0101));
    assert_eq!(canonical_scope_mask(&a), canonical_scope_mask(&b));
}

#[test]
fn mask_round_trips_to_sorted_scopes() {
    let env = Env::default();
    for mask in 1u32..16 {
        let expanded = scopes_from_mask(&env, mask);
        assert_eq!(canonical_scope_mask(&expanded), Some(mask));
    }
    assert_eq!(
        scopes_from_mask(&env, 0b1010),
        scopes(
            &env,
            &[ConsentScope::WriteMedical, ConsentScope::EmergencyOnly]
        )
    );
}

#[test]
fn empty_or_oversized_scope_lists_are_rejected() {
    let (env, client, pet_id) = setup();
    let grantee = Address::generate(&env);

    let err = client
        .try_grant_canonical_consent(&pet_id, &grantee, &ConsentType::Research, &Vec::new(&env))
        .unwrap_err()
        .unwrap();
    assert_eq!(err, ContractError::InvalidInput.into());

    let mut too_many = Vec::new(&env);
    for _ in 0..=MAX_CONSENT_SCOPE_INPUT {
        too_many.push_back(ConsentScope::ReadMedical);
    }
    let err = client
        .try_grant_canonical_consent(&pet_id, &grantee, &ConsentType::Research, &too_many)
        .unwrap_err()
        .unwrap();
    assert_eq!(err, ContractError::InvalidInput.into());
}

// --- hash vectors / collisions ---

#[test]
fn hash_vectors_match_reference_implementation() {
    let env = Env::default();
    let s1 = subject(&env, SUBJECT_1);
    let s2 = subject(&env, SUBJECT_2);
    let lab_med = scopes(&env, &[ConsentScope::ReadLab, ConsentScope::ReadMedical]);

    let cases = [
        (
            1u64,
            &s1,
            ConsentType::Research,
            lab_med.clone(),
            1u32,
            RESEARCH_READ_MEDICAL_LAB_V1,
        ),
        (
            1,
            &s1,
            ConsentType::Research,
            lab_med,
            2,
            RESEARCH_READ_MEDICAL_LAB_V2,
        ),
        (
            7,
            &s2,
            ConsentType::Insurance,
            scopes(&env, &ALL_SCOPES),
            1,
            INSURANCE_ALL_SCOPES_V1,
        ),
    ];
    for (pet, subj, purpose, sc, version, expected) in cases {
        let mask = canonical_scope_mask(&sc).unwrap();
        let hash = canonical_consent_hash(&env, pet, subj, purpose_code(&purpose), mask, version);
        assert_eq!(hash, BytesN::from_array(&env, &hex_to_array(expected)));
    }
}

#[test]
fn granted_consent_hash_matches_published_vector() {
    let (env, client, pet_id) = setup();
    assert_eq!(pet_id, 1);
    let consent = client.grant_canonical_consent(
        &pet_id,
        &subject(&env, SUBJECT_1),
        &ConsentType::Research,
        &scopes(&env, &[ConsentScope::ReadMedical, ConsentScope::ReadLab]),
    );
    assert_eq!(
        consent.consent_hash,
        BytesN::from_array(&env, &hex_to_array(RESEARCH_READ_MEDICAL_LAB_V1))
    );
}

#[test]
fn every_distinct_scope_set_has_a_distinct_hash() {
    let env = Env::default();
    let s = subject(&env, SUBJECT_1);
    let mut seen: Vec<BytesN<32>> = Vec::new(&env);
    for mask in 1u32..16 {
        let sc = scopes_from_mask(&env, mask);
        let hash = canonical_consent_hash(
            &env,
            1,
            &s,
            purpose_code(&ConsentType::Research),
            canonical_scope_mask(&sc).unwrap(),
            1,
        );
        assert!(!seen.contains(&hash), "collision for mask {mask}");
        seen.push_back(hash);
    }
}

#[test]
fn hash_binds_pet_subject_purpose_and_version() {
    let env = Env::default();
    let s1 = subject(&env, SUBJECT_1);
    let s2 = subject(&env, SUBJECT_2);
    let base = canonical_consent_hash(&env, 1, &s1, 2, 0b0101, 1);

    assert_ne!(base, canonical_consent_hash(&env, 2, &s1, 2, 0b0101, 1));
    assert_ne!(base, canonical_consent_hash(&env, 1, &s2, 2, 0b0101, 1));
    assert_ne!(base, canonical_consent_hash(&env, 1, &s1, 3, 0b0101, 1));
    assert_ne!(base, canonical_consent_hash(&env, 1, &s1, 2, 0b0101, 2));
}

#[test]
fn compute_hash_entrypoint_matches_library_function() {
    let (env, client, pet_id) = setup();
    let s = subject(&env, SUBJECT_1);
    let sc = scopes(
        &env,
        &[
            ConsentScope::ReadLab,
            ConsentScope::ReadMedical,
            ConsentScope::ReadLab,
        ],
    );
    assert_eq!(
        client.compute_canonical_consent_hash(&pet_id, &s, &ConsentType::Research, &sc, &1),
        canonical_consent_hash(&env, pet_id, &s, 2, 0b0101, 1)
    );
}

// --- grant lifecycle ---

#[test]
fn equivalent_grants_produce_one_canonical_consent() {
    let (env, client, pet_id) = setup();
    let grantee = Address::generate(&env);

    let first = client.grant_canonical_consent(
        &pet_id,
        &grantee,
        &ConsentType::Research,
        &scopes(&env, &[ConsentScope::ReadLab, ConsentScope::ReadMedical]),
    );
    env.ledger().with_mut(|l| l.timestamp = T0 + 1_000);
    let second = client.grant_canonical_consent(
        &pet_id,
        &grantee,
        &ConsentType::Research,
        &scopes(
            &env,
            &[
                ConsentScope::ReadMedical,
                ConsentScope::ReadLab,
                ConsentScope::ReadMedical,
            ],
        ),
    );

    assert_eq!(first, second);
    assert_eq!(second.version, 1);
    assert_eq!(second.granted_at, T0);
    assert_eq!(
        client.get_latest_canonical_consent(&pet_id, &grantee, &ConsentType::Research),
        Some(first)
    );
}

#[test]
fn different_terms_create_a_new_version_and_supersede_the_old() {
    let (env, client, pet_id) = setup();
    let grantee = Address::generate(&env);

    let v1 = client.grant_canonical_consent(
        &pet_id,
        &grantee,
        &ConsentType::Research,
        &scopes(&env, &[ConsentScope::ReadMedical]),
    );
    let v2 = client.grant_canonical_consent(
        &pet_id,
        &grantee,
        &ConsentType::Research,
        &scopes(&env, &[ConsentScope::ReadLab]),
    );

    assert_eq!(v2.version, 2);
    assert_ne!(v1.consent_hash, v2.consent_hash);
    let old = client.get_canonical_consent(&v1.consent_hash).unwrap();
    assert_eq!(old.status, CanonicalConsentStatus::Superseded);
    assert_eq!(old.ended_at, Some(T0));

    assert!(!client.has_canonical_consent_scope(
        &pet_id,
        &grantee,
        &ConsentType::Research,
        &ConsentScope::ReadMedical
    ));
    assert!(client.has_canonical_consent_scope(
        &pet_id,
        &grantee,
        &ConsentType::Research,
        &ConsentScope::ReadLab
    ));
}

#[test]
fn different_purposes_are_independent_lines() {
    let (env, client, pet_id) = setup();
    let grantee = Address::generate(&env);
    let sc = scopes(&env, &[ConsentScope::ReadMedical]);

    let research = client.grant_canonical_consent(&pet_id, &grantee, &ConsentType::Research, &sc);
    let insurance = client.grant_canonical_consent(&pet_id, &grantee, &ConsentType::Insurance, &sc);

    assert_ne!(research.consent_hash, insurance.consent_hash);
    assert_eq!(insurance.version, 1);
    assert_eq!(
        client
            .get_canonical_consent(&research.consent_hash)
            .unwrap()
            .status,
        CanonicalConsentStatus::Active
    );
}

// --- revocation targets the exact version ---

#[test]
fn revocation_targets_the_exact_active_version() {
    let (env, client, pet_id) = setup();
    let grantee = Address::generate(&env);
    let c = client.grant_canonical_consent(
        &pet_id,
        &grantee,
        &ConsentType::Research,
        &scopes(&env, &[ConsentScope::ReadMedical]),
    );

    env.ledger().with_mut(|l| l.timestamp = T0 + 500);
    let revoked = client.revoke_canonical_consent(&pet_id, &c.consent_hash);
    assert_eq!(revoked.status, CanonicalConsentStatus::Revoked);
    assert_eq!(revoked.ended_at, Some(T0 + 500));
    assert!(!client.has_canonical_consent_scope(
        &pet_id,
        &grantee,
        &ConsentType::Research,
        &ConsentScope::ReadMedical
    ));
}

#[test]
fn stale_revocation_cannot_hit_a_newer_version() {
    let (env, client, pet_id) = setup();
    let grantee = Address::generate(&env);
    let v1 = client.grant_canonical_consent(
        &pet_id,
        &grantee,
        &ConsentType::Research,
        &scopes(&env, &[ConsentScope::ReadMedical]),
    );
    let v2 = client.grant_canonical_consent(
        &pet_id,
        &grantee,
        &ConsentType::Research,
        &scopes(&env, &[ConsentScope::ReadMedical, ConsentScope::ReadLab]),
    );

    let err = client
        .try_revoke_canonical_consent(&pet_id, &v1.consent_hash)
        .unwrap_err()
        .unwrap();
    assert_eq!(err, ContractError::ConsentVersionMismatch.into());
    assert_eq!(
        client
            .get_canonical_consent(&v2.consent_hash)
            .unwrap()
            .status,
        CanonicalConsentStatus::Active
    );
}

#[test]
fn revoked_version_is_not_resurrected_by_regranting() {
    let (env, client, pet_id) = setup();
    let grantee = Address::generate(&env);
    let sc = scopes(&env, &[ConsentScope::ReadMedical]);

    let v1 = client.grant_canonical_consent(&pet_id, &grantee, &ConsentType::Research, &sc);
    client.revoke_canonical_consent(&pet_id, &v1.consent_hash);

    let err = client
        .try_revoke_canonical_consent(&pet_id, &v1.consent_hash)
        .unwrap_err()
        .unwrap();
    assert_eq!(err, ContractError::ConsentVersionMismatch.into());

    // Same terms again: a fresh version with a fresh hash.
    let v2 = client.grant_canonical_consent(&pet_id, &grantee, &ConsentType::Research, &sc);
    assert_eq!(v2.version, 2);
    assert_ne!(v2.consent_hash, v1.consent_hash);
    assert_eq!(
        client
            .get_canonical_consent(&v1.consent_hash)
            .unwrap()
            .status,
        CanonicalConsentStatus::Revoked
    );
}

#[test]
fn revocation_with_a_hash_from_another_pet_is_rejected() {
    let (env, client, pet_id) = setup();
    let other_pet = register_pet(&env, &client);
    let grantee = Address::generate(&env);
    let c = client.grant_canonical_consent(
        &pet_id,
        &grantee,
        &ConsentType::Research,
        &scopes(&env, &[ConsentScope::ReadMedical]),
    );

    let err = client
        .try_revoke_canonical_consent(&other_pet, &c.consent_hash)
        .unwrap_err()
        .unwrap();
    assert_eq!(err, ContractError::ConsentNotFound.into());

    let unknown = BytesN::from_array(&env, &[9u8; 32]);
    let err = client
        .try_revoke_canonical_consent(&pet_id, &unknown)
        .unwrap_err()
        .unwrap();
    assert_eq!(err, ContractError::ConsentNotFound.into());
}
